name: CI/CD

on:
  push:
    branches:
      - master

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build project
        run: pnpm run build

      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          pnpm publish --access public
          echo "Published to npm"

      - name: Create GitHub release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            ${{ steps.generate_changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Generate changelog
        id: generate_changelog
        run: |
          echo "::set-output name=changelog::$(git log --pretty=format:'- %s' | grep -E 'feat:|fix:|perf:|refactor:|revert:|docs:|chore:|ci:|test:||wip:')"
